### ISSUE TITLE
Feature request: Dynamic box width using text indentation

### ISSUE THREAD

**Issue by dgraber95** [slysherz/vscode-comment-box#11]
First, thanks for this extension. It makes commenting lines in a specific format so much easier, and I already love it.

The only improvement I can think of is an option like "boxEndingColumn" or something similar. I like to have all my comments end on the same column, regardless of the indentation of the text being commented. I think it could either override boxWidth, or work in addition to it - either would work for me. 

For example, if I have three lines starting at column 0, column 4, and column 8, with a boxEndingColumn setting of 60, the commented lines would look like this: 

![image](https://user-images.githubusercontent.com/21182140/135280795-b2f58a25-e792-44c5-9108-70dfc7a9b5ea.png)

Like I said, very happy with the extension as is, this one little thing would make it perfect for me though. Thanks again!

**Comment by slysherz** [comment]
Hey @dgraber95 , I'm glad you're enjoying it : )

Your suggestion seems pretty useful, I wonder how I've never thought about it. It's also quite simple to implement, I should be able to sneak it in for the next update (it's almost ready).

I'm thinking about a new `maxEndColumn` setting, so if you set a high `boxWidth` value (60 too) it should do exactly what you want. It has the added benefit that people who prefer fixed size boxes can use it too. What do you think?

**Comment by dgraber95** [comment]
That's actually exactly what I was picturing. If you have both, set the width to whichever is less between maxEndColumn and boxWidth.

**Comment by slysherz** [comment]
I released this last weekend, did you have a chance to try it @dgraber95 ?

**Comment by slysherz** [comment]
Great! Closing.
