### ISSUE TITLE
feature requests: uncomment comment box

### ISSUE THREAD

**Issue by xuestrange** [slysherz/vscode-comment-box#14]
as title says

**Comment by slysherz** [comment]
Hey @xuestrange , you should already be able to do this with the Remove Comment Box command.

https://github.com/slysherz/vscode-comment-box/blob/master/images/usage-example.gif

(check the end of the gif)

**Comment by xuestrange** [comment]
Thank you! you're so sweet. I should remove and update comment box with **the same style** which I customize for myself. It's really powerful and easy-use, good job!

**Comment by slysherz** [comment]
Thanks for the kind words : )

> I should remove and update comment box with the same style

Yes, for now you have to do that. In the future I intend to make it detect the right style automatically, but that will take a while.
