### ISSUE TITLE
[Request] Alignment to the RIGHT

### ISSUE THREAD

**Issue by Xelbayria** [slysherz/vscode-comment-box#19]
The title is pretty much self-explanatory. I would like to use ` "textAlignment": "right" ` and it will be useful for me and some people.

**Comment by slysherz** [comment]
I agree this could be useful, and it seems easy to implement. Thanks for the suggestion, I'll see what I can do : )

**Comment by slysherz** [comment]
Done, let me know if it does what you expected.

**Comment by Xelbayria** [comment]
> Done, let me know if it does what you expected.

alright, i'll check out the new feature. will let you know how it turned out
