### ISSUE TITLE
Maximum width

### ISSUE THREAD

**Issue by jani-r** [slysherz/vscode-comment-box#24]
Thx for this great extension. One option which would make it even better would be an option to set the maximum width. Currently when setting the width option, the comment box is always this long. However with intended lines it would be very nice to be able to set the maximum width the box will use.

**Comment by slysherz** [comment]
Hey @jani-r, thanks for the suggestion. Are you aware of the `maxEndColumn` option? I think it does what you are suggesting, but it not please let me know : )

**Comment by jani-r** [comment]
Thank you!  I didn't notice this option as it was not listed in [README.md](https://github.com/slysherz/vscode-comment-box/blob/master/README.md).

Based on the source file there are maybe even few more options not listed: "wordWrap" and "tabSize"?
