### ISSUE TITLE
Feature request: Remove comment box, or allow adding rows

### ISSUE THREAD

**Issue by d1820** [slysherz/vscode-comment-box#7]
Would be very helpful to be able to add new rows to a set of boxed comments and have the extension detect the new rows and just add the delimiters to those rows, or at least remove the existing comment box and regenerate again to account for new rows being added. As of now you can pretty much only use it once, and most documentation grows over time

![image](https://user-images.githubusercontent.com/377631/113007524-25478f00-912b-11eb-80be-af9466e4e6bf.png)

double wraps

![image](https://user-images.githubusercontent.com/377631/113007655-3f816d00-912b-11eb-91f5-cb0ed814dde8.png)

**Comment by slysherz** [comment]
Hello, and thanks for the feedback!

I've been looking into this and I think it's very useful, I'll try to add it soon.

There are a few things we can do:
- remove a comment box selected by the user
- add a new line in the middle of the comment box (assuming the user picked the same style)
- detect that the current line is in the middle of a comment box and update it accordingly

IMO option 3 would be really nice, but it is really hard to implement and super easy to mess up, so I'll leave that for later. Meanwhile, I'll try to implement 1 and 2 and see how it works out.

**Comment by slysherz** [comment]
I just released the new 2.1 update, with new commands to remove and update comment boxes, enjoy : )

For now you'll have to select all lines to update / remove a comment box - in the future I'll try to make it automatically detect where boxes start and end.
